-- Team Talk material request workflow.
-- Prepared on a work branch only. Do not apply to production until the PC layout integration is ready.

create table if not exists public.olli_team_material_requests (
  id uuid primary key default extensions.gen_random_uuid(),
  academy_id uuid not null references public.academies(id) on delete cascade,
  item_name text not null,
  quantity_text text not null default '1개',
  needed_on date,
  use_context text,
  purchase_url text,
  memo text,
  status text not null default 'requested',
  hold_reason text,
  requested_by_member_id uuid not null references public.academy_members(id),
  requested_by_name_snapshot text not null,
  status_changed_by_member_id uuid references public.academy_members(id),
  status_changed_at timestamptz not null default now(),
  ordered_at timestamptz,
  ordered_by_member_id uuid references public.academy_members(id),
  arrived_at timestamptz,
  arrived_by_member_id uuid references public.academy_members(id),
  revision bigint not null default 1,
  client_mutation_id uuid not null default extensions.gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint olli_team_material_requests_item_name_check
    check (char_length(btrim(item_name)) between 1 and 120),
  constraint olli_team_material_requests_quantity_text_check
    check (char_length(btrim(quantity_text)) between 1 and 60),
  constraint olli_team_material_requests_use_context_check
    check (use_context is null or char_length(btrim(use_context)) <= 160),
  constraint olli_team_material_requests_purchase_url_check
    check (
      purchase_url is null
      or (
        char_length(btrim(purchase_url)) <= 2000
        and btrim(purchase_url) ~* '^https?://'
      )
    ),
  constraint olli_team_material_requests_memo_check
    check (memo is null or char_length(memo) <= 1000),
  constraint olli_team_material_requests_hold_reason_check
    check (hold_reason is null or char_length(hold_reason) <= 500),
  constraint olli_team_material_requests_status_check
    check (status in ('requested','on_hold','ordered','arrived')),
  constraint olli_team_material_requests_revision_check
    check (revision >= 1),
  constraint olli_team_material_requests_client_mutation_unique
    unique (academy_id, client_mutation_id)
);

create index if not exists olli_team_material_requests_academy_status_needed_idx
  on public.olli_team_material_requests (academy_id, status, needed_on, created_at desc)
  where deleted_at is null;

create index if not exists olli_team_material_requests_academy_created_idx
  on public.olli_team_material_requests (academy_id, created_at desc)
  where deleted_at is null;

create table if not exists public.olli_team_material_request_events (
  id bigint generated by default as identity primary key,
  academy_id uuid not null references public.academies(id) on delete cascade,
  request_id uuid not null references public.olli_team_material_requests(id) on delete cascade,
  member_id uuid references public.academy_members(id),
  event_type text not null,
  from_status text,
  to_status text,
  note text,
  created_at timestamptz not null default now(),
  constraint olli_team_material_request_events_type_check
    check (event_type in ('created','status_changed')),
  constraint olli_team_material_request_events_from_status_check
    check (from_status is null or from_status in ('requested','on_hold','ordered','arrived')),
  constraint olli_team_material_request_events_to_status_check
    check (to_status is null or to_status in ('requested','on_hold','ordered','arrived')),
  constraint olli_team_material_request_events_note_check
    check (note is null or char_length(note) <= 500)
);

create index if not exists olli_team_material_request_events_request_idx
  on public.olli_team_material_request_events (request_id, id desc);

alter table public.olli_team_material_requests enable row level security;
alter table public.olli_team_material_request_events enable row level security;

revoke all on public.olli_team_material_requests from anon, authenticated;
revoke all on public.olli_team_material_request_events from anon, authenticated;

create or replace function public.olli_team_material_requests_list(
  p_session_token text,
  p_academy_id uuid,
  p_limit integer default 300
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_account_id uuid;
  v_member public.academy_members%rowtype;
  v_limit integer := greatest(1, least(coalesce(p_limit, 300), 500));
  v_items jsonb;
  v_summary jsonb;
begin
  v_account_id := public.olli_account_id_from_session(p_session_token);
  if v_account_id is null then
    raise exception '로그인 세션이 만료되었거나 올바르지 않습니다.';
  end if;

  select m.*
    into v_member
  from public.academy_members m
  join public.academies a on a.id = m.academy_id
  where m.academy_id = p_academy_id
    and m.account_id = v_account_id
    and m.status = 'active'
    and a.status = 'active'
    and a.deleted_at is null
  order by
    case m.role when 'owner' then 1 when 'manager' then 2 when 'teacher' then 3 else 4 end,
    m.created_at
  limit 1;

  if v_member.id is null then
    raise exception '현재 계정은 이 학원의 재료주문을 사용할 수 없습니다.';
  end if;

  select jsonb_build_object(
    'requested', count(*) filter (where r.status = 'requested'),
    'on_hold', count(*) filter (where r.status = 'on_hold'),
    'ordered', count(*) filter (where r.status = 'ordered'),
    'arrived', count(*) filter (where r.status = 'arrived')
  )
    into v_summary
  from public.olli_team_material_requests r
  where r.academy_id = p_academy_id
    and r.deleted_at is null;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', x.id,
        'item_name', x.item_name,
        'quantity_text', x.quantity_text,
        'needed_on', x.needed_on,
        'use_context', x.use_context,
        'purchase_url', x.purchase_url,
        'memo', x.memo,
        'status', x.status,
        'hold_reason', x.hold_reason,
        'requested_by_member_id', x.requested_by_member_id,
        'requested_by_name', x.requested_by_name_snapshot,
        'status_changed_by_member_id', x.status_changed_by_member_id,
        'status_changed_by_name', x.status_changed_by_name,
        'status_changed_at', x.status_changed_at,
        'ordered_at', x.ordered_at,
        'arrived_at', x.arrived_at,
        'revision', x.revision,
        'created_at', x.created_at,
        'updated_at', x.updated_at
      )
      order by
        case x.status when 'requested' then 1 when 'on_hold' then 2 when 'ordered' then 3 when 'arrived' then 4 else 5 end,
        x.needed_on nulls last,
        x.created_at desc
    ),
    '[]'::jsonb
  )
    into v_items
  from (
    select
      r.*,
      changed.display_name as status_changed_by_name
    from public.olli_team_material_requests r
    left join public.academy_members changed on changed.id = r.status_changed_by_member_id
    where r.academy_id = p_academy_id
      and r.deleted_at is null
    order by
      case r.status when 'requested' then 1 when 'on_hold' then 2 when 'ordered' then 3 when 'arrived' then 4 else 5 end,
      r.needed_on nulls last,
      r.created_at desc
    limit v_limit
  ) x;

  return jsonb_build_object(
    'ok', true,
    'academy_id', p_academy_id,
    'current_member_id', v_member.id,
    'current_role', v_member.role,
    'can_process', v_member.role in ('owner','manager'),
    'summary', coalesce(v_summary, '{}'::jsonb),
    'items', coalesce(v_items, '[]'::jsonb)
  );
end;
$function$;

create or replace function public.olli_team_material_request_create(
  p_session_token text,
  p_academy_id uuid,
  p_item_name text,
  p_quantity_text text,
  p_needed_on date default null,
  p_use_context text default null,
  p_purchase_url text default null,
  p_memo text default null,
  p_client_mutation_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_account_id uuid;
  v_member public.academy_members%rowtype;
  v_request public.olli_team_material_requests%rowtype;
  v_item_name text := btrim(coalesce(p_item_name, ''));
  v_quantity_text text := btrim(coalesce(p_quantity_text, ''));
  v_use_context text := nullif(btrim(coalesce(p_use_context, '')), '');
  v_purchase_url text := nullif(btrim(coalesce(p_purchase_url, '')), '');
  v_memo text := nullif(btrim(coalesce(p_memo, '')), '');
  v_client_mutation_id uuid := coalesce(p_client_mutation_id, extensions.gen_random_uuid());
begin
  v_account_id := public.olli_account_id_from_session(p_session_token);
  if v_account_id is null then
    raise exception '로그인 세션이 만료되었거나 올바르지 않습니다.';
  end if;

  select m.*
    into v_member
  from public.academy_members m
  join public.academies a on a.id = m.academy_id
  where m.academy_id = p_academy_id
    and m.account_id = v_account_id
    and m.status = 'active'
    and a.status = 'active'
    and a.deleted_at is null
  order by
    case m.role when 'owner' then 1 when 'manager' then 2 when 'teacher' then 3 else 4 end,
    m.created_at
  limit 1;

  if v_member.id is null then
    raise exception '현재 계정은 이 학원의 재료주문을 사용할 수 없습니다.';
  end if;

  if char_length(v_item_name) < 1 or char_length(v_item_name) > 120 then
    raise exception '재료명은 1~120자로 입력해 주세요.';
  end if;
  if char_length(v_quantity_text) < 1 or char_length(v_quantity_text) > 60 then
    raise exception '수량은 1~60자로 입력해 주세요.';
  end if;
  if v_use_context is not null and char_length(v_use_context) > 160 then
    raise exception '사용수업은 160자 이내로 입력해 주세요.';
  end if;
  if v_purchase_url is not null and (char_length(v_purchase_url) > 2000 or v_purchase_url !~* '^https?://') then
    raise exception '구매링크는 http 또는 https 주소로 입력해 주세요.';
  end if;
  if v_memo is not null and char_length(v_memo) > 1000 then
    raise exception '메모는 1000자 이내로 입력해 주세요.';
  end if;

  insert into public.olli_team_material_requests (
    academy_id,
    item_name,
    quantity_text,
    needed_on,
    use_context,
    purchase_url,
    memo,
    status,
    requested_by_member_id,
    requested_by_name_snapshot,
    status_changed_by_member_id,
    client_mutation_id
  )
  values (
    p_academy_id,
    v_item_name,
    v_quantity_text,
    p_needed_on,
    v_use_context,
    v_purchase_url,
    v_memo,
    'requested',
    v_member.id,
    v_member.display_name,
    v_member.id,
    v_client_mutation_id
  )
  on conflict (academy_id, client_mutation_id) do nothing
  returning * into v_request;

  if v_request.id is null then
    select r.*
      into v_request
    from public.olli_team_material_requests r
    where r.academy_id = p_academy_id
      and r.client_mutation_id = v_client_mutation_id
    limit 1;
  else
    insert into public.olli_team_material_request_events (
      academy_id, request_id, member_id, event_type, to_status
    )
    values (
      p_academy_id, v_request.id, v_member.id, 'created', 'requested'
    );
    perform private.olli_realtime_send_signal(p_academy_id, 'chat', v_request.revision);
  end if;

  return jsonb_build_object(
    'ok', true,
    'request_id', v_request.id,
    'revision', v_request.revision,
    'status', v_request.status
  );
end;
$function$;

create or replace function public.olli_team_material_request_set_status(
  p_session_token text,
  p_academy_id uuid,
  p_request_id uuid,
  p_status text,
  p_expected_revision bigint,
  p_hold_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_account_id uuid;
  v_member public.academy_members%rowtype;
  v_request public.olli_team_material_requests%rowtype;
  v_status text := lower(btrim(coalesce(p_status, '')));
  v_hold_reason text := nullif(btrim(coalesce(p_hold_reason, '')), '');
  v_previous_status text;
begin
  v_account_id := public.olli_account_id_from_session(p_session_token);
  if v_account_id is null then
    raise exception '로그인 세션이 만료되었거나 올바르지 않습니다.';
  end if;

  select m.*
    into v_member
  from public.academy_members m
  join public.academies a on a.id = m.academy_id
  where m.academy_id = p_academy_id
    and m.account_id = v_account_id
    and m.status = 'active'
    and a.status = 'active'
    and a.deleted_at is null
  order by
    case m.role when 'owner' then 1 when 'manager' then 2 else 3 end,
    m.created_at
  limit 1;

  if v_member.id is null or v_member.role not in ('owner','manager') then
    raise exception '재료 주문 상태는 원장 또는 관리자만 변경할 수 있습니다.';
  end if;

  if v_status not in ('requested','on_hold','ordered','arrived') then
    raise exception '재료 주문 상태 값을 확인해 주세요.';
  end if;
  if v_hold_reason is not null and char_length(v_hold_reason) > 500 then
    raise exception '보류 사유는 500자 이내로 입력해 주세요.';
  end if;

  select r.status
    into v_previous_status
  from public.olli_team_material_requests r
  where r.id = p_request_id
    and r.academy_id = p_academy_id
    and r.deleted_at is null;

  if v_previous_status is null then
    raise exception '재료 요청을 찾지 못했습니다.';
  end if;

  update public.olli_team_material_requests r
  set
    status = v_status,
    hold_reason = case when v_status = 'on_hold' then v_hold_reason else null end,
    status_changed_by_member_id = v_member.id,
    status_changed_at = now(),
    ordered_at = case
      when v_status = 'ordered' then coalesce(r.ordered_at, now())
      when v_status in ('requested','on_hold') then null
      else r.ordered_at
    end,
    ordered_by_member_id = case
      when v_status = 'ordered' then v_member.id
      when v_status in ('requested','on_hold') then null
      else r.ordered_by_member_id
    end,
    arrived_at = case
      when v_status = 'arrived' then coalesce(r.arrived_at, now())
      else null
    end,
    arrived_by_member_id = case
      when v_status = 'arrived' then v_member.id
      else null
    end,
    revision = r.revision + 1,
    updated_at = now()
  where r.id = p_request_id
    and r.academy_id = p_academy_id
    and r.deleted_at is null
    and r.revision = p_expected_revision
  returning r.* into v_request;

  if v_request.id is null then
    if exists (
      select 1
      from public.olli_team_material_requests r
      where r.id = p_request_id
        and r.academy_id = p_academy_id
        and r.deleted_at is null
    ) then
      raise exception '다른 기기에서 재료 상태가 먼저 변경되었습니다. 최신 상태를 다시 불러와 주세요.';
    end if;
    raise exception '재료 요청을 찾지 못했습니다.';
  end if;

  insert into public.olli_team_material_request_events (
    academy_id,
    request_id,
    member_id,
    event_type,
    from_status,
    to_status,
    note
  )
  values (
    p_academy_id,
    v_request.id,
    v_member.id,
    'status_changed',
    v_previous_status,
    v_status,
    case when v_status = 'on_hold' then v_hold_reason else null end
  );

  perform private.olli_realtime_send_signal(p_academy_id, 'chat', v_request.revision);

  return jsonb_build_object(
    'ok', true,
    'request_id', v_request.id,
    'status', v_request.status,
    'revision', v_request.revision,
    'updated_at', v_request.updated_at
  );
end;
$function$;

revoke all on function public.olli_team_material_requests_list(text, uuid, integer) from public;
revoke all on function public.olli_team_material_request_create(text, uuid, text, text, date, text, text, text, uuid) from public;
revoke all on function public.olli_team_material_request_set_status(text, uuid, uuid, text, bigint, text) from public;

grant execute on function public.olli_team_material_requests_list(text, uuid, integer) to anon, authenticated;
grant execute on function public.olli_team_material_request_create(text, uuid, text, text, date, text, text, text, uuid) to anon, authenticated;
grant execute on function public.olli_team_material_request_set_status(text, uuid, uuid, text, bigint, text) to anon, authenticated;
